sprint is completed
alextim1508/java-shareit pull request #5
Opened 2022-12-25 16:12 UTC by alextim1508

2022-12-27 00:58 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-27 00:58 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private static final String DEFAULT_PAGE_SIZE = "100";
Хм... зуб даю у тебя есть еще один контроллер, а может и не один! 
В котором тоже прописана такая константа!

Подумай над тем, куда бы это вынести, чтобы не писать код дважды!

2022-12-27 00:58 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                   BindingResult result) {
Ты подключаешь BindingResult по причине того что по другому не заработала валидация?

2022-12-27 00:58 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public List<? extends BookingDtoOutAbs> getAllByBooker(@RequestParam(value = "state", required = false, defaultValue = "ALL") String state,
Что то жуткое у тебя происходит с этим `? extends BookingDtoOutAbs`.
Оно явно избыточно, но мы сейчас это не разрулим слишком много времени уйдет. Оставим как есть.

2022-12-27 00:58 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                           @Min(0) @RequestParam(value = "from", required = false, defaultValue = "0") Integer from,
Нельзя чтобы строки вылазили за 120 символов.
Делай переносы в таких случаях.

```
    public List<? extends BookingDtoOutAbs> getAllByBooker(
            @RequestParam(value = "state", required = false, defaultValue = "ALL") String state,
            @RequestHeader(value = USER_ID_HEADER) int userId,
            @Min(0) @RequestParam(value = "from", required = false, defaultValue = "0") Integer from,
            @Min(1) @RequestParam(value = "size", required = false, defaultValue = DEFAULT_PAGE_SIZE) Integer size) {
        switch (state) {
........
```

2022-12-27 00:58 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public boolean equals(Object o) {
В данном случае, так как вы это не изучали лучше не переопределять эти два метода.
В среднем случае приложению достаточно дефолтных реализаций. Но так же есть и те случаи кода требуется кастомная реализация, т. к. это может существенно увеличить производительность приложения, либо ухудшить, в случае если вы допустили ошибку.

2022-12-27 00:58 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingMapper.java
> +    @Mapping(source = "bookingDto.itemId", target = "item")
Применение либы для маппинга это сильный ход! Молодец!

2022-12-27 00:58 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>              throw new ForbiddenException();
Не оставляй эксепшены без пояснений что произошло!
Всегда давай пояснения...
Не только в лог, но и в ексепшн.

2022-12-27 00:58 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return bookingMapper.toDto(bookings);
Есть хорошая практика делать отступ, в виде пустой строки, перед `return`.

Это выделяет точку выхода из метода визуально.
Есть только одно исключение: если метод начался сразу с return то отступ делать не нужно.

2022-12-27 00:58 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    private static final String DEFAULT_PAGE_SIZE = "100";
Вот оно! ))

2022-12-27 00:58 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> +    Collection<ItemRequest> findAll();
Collection -> List

2022-12-27 00:58 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/util/exception/ActionIsNotAvailableException.java
> +public class ActionIsNotAvailableException extends RuntimeException {
Не нужно создавать кучу классов, если ты в конечном итоге обрабатываешь это как BAD_REQUEST то и должен быть один класс BadRequestException.
А причины для того чтобы кидать этот ексепшн могут быть разными...

2022-12-27 00:58 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/util/exception/ItemIsNotAvailableException.java
> +public class ItemIsNotAvailableException extends RuntimeException {
Не нужен этот класс - уже есть один NotFoundException

2022-12-27 00:58 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/util/exception/StatusChangeException.java
>  public class StatusChangeException extends RuntimeException {
Это тоже один из случаев BAD_REQUEST

2022-12-27 08:53 UTC, alextim1508 commented on src/main/java/ru/practicum/shareit/util/exception/ActionIsNotAvailableException.java
> +public class ActionIsNotAvailableException extends RuntimeException {
Я исходил из такой логики. 
Сегодня на этот эксепнш мы возвращаем к примеру NotFound, а завтра на фронтенде решили, что нужно возвращать BadRequest.
В этом случае мы просто в ErrorHandler изменили код ошибки и нам не нужно лесть в несколько сервисов и изменять класс экспепшна.

2022-12-27 08:59 UTC, alextim1508 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public boolean equals(Object o) {
Не понял комментарий)
Почему мы не изучали equals? Изучали.
В проекте, к примеру, есть Item, у которого есть поля поля bookings, comments, lastBooking, nextBooking. И для него дефолтный equals и hashCode никак не подойдет.
Да и Idea ругается на аннотацию @EqualsAndHashCode и просит, чтобы методы были явно определены.

2022-12-27 09:04 UTC, alextim1508 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                   BindingResult result) {
Вполне может быть)

2022-12-27 09:11 UTC, alextim1508 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public List<? extends BookingDtoOutAbs> getAllByBooker(@RequestParam(value = "state", required = false, defaultValue = "ALL") String state,
Я решил использовать несколько Dto для одного класса. На пример, ItemDtoIn, ItemDtoOut, FullItemDtoOut. 
Есть сервис, который для владельца вещи возвращает FullItemDtoOut, а для не владельца - ItemDtoOut.
Поэтому я ввел абстрактный класс ItemDtoOutAbs. Таким образом все методы сервиса стали работать не с реализацией абстрактного класса (FullItemDtoOut и ItemDtoOut), а с абстрактным классом ItemDtoOutAbs.
Так и появился List<? extends BookingDtoOutAbs>.

2022-12-27 09:12 UTC, alextim1508 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private static final String DEFAULT_PAGE_SIZE = "100";
Ну да, можно запихнуть константу в какой- нибудь утилитный класс

2022-12-27 09:17 UTC, alextim1508 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public List<? extends BookingDtoOutAbs> getAllByBooker(@RequestParam(value = "state", required = false, defaultValue = "ALL") String state,
Разные dto я ввел по причине простоты тестирования и по причине безопасности.
Если бы мы работали только с одни dto напрмер FullItemDtoOut. То пользователь мог бы прислать его, маппер автоматически все его поля смапил в Item (например неправильно сконфигурировали маппер) и сервис его сохранил в базу данных.

2022-12-28 19:33 UTC, FanaticFiz approved these changes

2022-12-28 19:52 UTC, FanaticFiz approved these changes

2023-01-01 18:55 UTC, merged