Sprint is done
alextim1508/java-shareit pull request #6
Opened 2023-01-09 19:40 UTC by alextim1508

2023-01-10 18:08 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-01-10 18:08 UTC, FanaticFiz commented on pom.xml
> +
Этот pom файл родительский все его зависимости будут у каждого из дочерних модуля. Т.е. например зависимость `spring-boot-starter-validation` будет во всех серверах что нежелательно. Так же и с остальными. Стоит четко разделить что и где будет.

2023-01-10 18:08 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +import reactor.core.publisher.Mono;
Ну давай рассказывай что мне с этим делать? ))
Вот представь что я новенький на твоем проекте и тебе нужно ввести меня в курс дела.
Я скачал проект и у меня нет таких пакетов и зависимостей! 
`Mono, reactor, reactive`

Что делать?!?! )))

2023-01-10 18:08 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingState.java
> +public enum BookingState {
Нигде не используется?

2023-01-10 18:08 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +    protected Mono<ResponseEntity<String>> patch(String path, Integer userId, Map<String, Object> parameters, String body) {
Не должно быть строк длиной более 120 символов

2023-01-10 18:08 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/util/ErrorHandler.java
> +        log.error("{} : {}", e.getClass().getSimpleName(), e.getMessage());
У тебя несколько обработчиков одинаковы, а ведь этого можно избежать, указав один для нескольких классов.

2023-01-10 18:17 UTC, alextim1508 commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingState.java
> +public enum BookingState {
Копи-паст)

2023-01-10 18:18 UTC, alextim1508 commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +    protected Mono<ResponseEntity<String>> patch(String path, Integer userId, Map<String, Object> parameters, String body) {
Это кстати взято из родительского проекта и этот класс делали авторы курса)

2023-01-10 19:14 UTC, alextim1508 commented on gateway/src/main/java/ru/practicum/shareit/util/ErrorHandler.java
> +        log.error("{} : {}", e.getClass().getSimpleName(), e.getMessage());
Согласен. Еще удалил обработчик для ValidationException. Когда писал кастомный валидатор (ныне удаленный), бросал это исключение. Думал, что именно ValidationException будет обрабатываться в ErrorHandler.
На деле любое исключение при валидации оборачивается в MethodArgumentNotValidException и оно уже обрабатывается

2023-01-10 21:08 UTC, alextim1508 commented on pom.xml
> +
Принято. Спасибо! Отличное замечание!

2023-01-11 20:47 UTC, FanaticFiz approved these changes

2023-01-11 20:51 UTC, merged